# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param x cash on hand grid
#' @param sigma_n standard deviation of log permanent income
#' @param sigma_u standard deviation of log transitory income
#' @param gamma_0 intercept of retirement MPC
#' @param gamma_1 slope of retirement MPC in cash on hand
#' @param R risk free rate
#' @param G permanent income growth rate
#' @param T number of years
#' @param beta time discount factor
#' @export
NULL

#' Solve a single step of the Euler period to period
#' @param c_next vector of next period consumption
#' @param x vector of cash on hand
#' @param R risk free rate
#' @param G growth rate of income
#' @param sigma_n standard deviation of log perm inc
#' @param sigma_u standard deviation of log temp inc
#' @param p_noinc probability that u = 0, no wage
#' @param beta time discount factor
NULL

#' Simple linear interpolation
#' @param z value to interpolate at
#' @param c function we are interpolating
#' @param x domain we are interpolating over
NULL

#' Finds the roots of a function that takes a double vector as input
#' @param f function to find the roots of
#' @param intervals matrix of intervals to search over
#' @param tol tolerance for what is equivalent to zero
#' @param max_iter max number of iterations
#' @details find the roots for each component of the vector
#' [[Rcpp::export]]
NULL

#' Linear interpolation
#' @param z input parameter to linearly interpolate the x coordinates
#' @param c output vector to weight based on the input
#' @details Returns a funtion that linearly interpolates
#' a function based on input vector z and output vector c
NULL

#' Compute marginal utility given parameters
#' @param c_now this period's consumption
#' @param c_tp1 next period's consumption
#' @param x cash on hand
#' @param R risk free rate
#' @param G growth rate of income
#' @param sigma_n sd of log permanent income
#' @param sigma_u sd of log temp. income
#' @param beta time discount factor
NULL

#' Computes the 2D Gaussian quadrature rule of order 12
NULL

consumption_path <- function(x, sigma_n, sigma_u, gamma_0, gamma_1, R, G, p_noinc, T) {
    .Call('_gp_consumption_path', PACKAGE = 'gp', x, sigma_n, sigma_u, gamma_0, gamma_1, R, G, p_noinc, T)
}

